name = "cleopatra-game"
main = "worker.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "CLEOPATRA_MEMORY", class_name = "CleopatraMemory" }
]

[[migrations]]
tag = "v1"
new_classes = ["CleopatraMemory"]
